apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: productcatalogservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - productcatalogservice.hipstershop-staging.demo2.keptn.live.demo.dynatrace.com
  - productcatalogservice
  http:
  - route:
    - destination:
        host: productcatalogservice.hipstershop-staging.svc.cluster.local
